#================================================================
#   Copyright (C) 2019  All rights reserved.
#   
#   文件名称：Makefile
#   创 建 者：MoZhiYe
#   创建日期：2019年03月31日 10:34:06
#   描    述：
#
#================================================================

obj_cpp = temp.cpp

target = out.exe

CC = g++

all:
	$(CC) -v $(obj_cpp) -o target

