#================================================================
#   Copyright (C) 2018  All rights reserved.
#   
#   文件名称：Makefile
#   创 建 者：MoZhiYe
#   创建日期：2018年07月15日 14:50:25
#   描    述：
#
#================================================================
export ROOT = $(abspath .)
CC=gcc
CFALG =-v -o 001.bin #终极目标
OBJ_DIR = $(ROOT)/objs
export OBJ_DIR
export CC
export CFALG

objs = main.o \

sub_objs := \

obj_ls = \

obj_bs = \

#添加头文件搜索路径,在c文件中直接写文件名就可以
export includes = \
-I$(ROOT)/include

GEN_DIR=n
ROOT_DIR=y

export sub_objs

include $(ROOT)/rule.mk



